 //   {
    //     name: "Florentine",
    //     imageSrc:
    //       "/public/topproducts/Joerger-Valencia-Edelmessing-mit-weissem-Kristall-Unterputz-Hebelmischer.jpg",
    //     //   details:' High-quality sanitaryware for your bathroom.'
    //     details: "",
    //     products: [
    //       {
    //         name: "PILLAR COCK",
    //         code: "FLTPCC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "LONG BODY WITH CP FLANGES",
    //         code: "FLTLBC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHTING",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "BIB COCK WITH CP FLANGES",
    //         code: "FLTBCC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN / KICTHEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "ANGLE COCK WITH CP FLANGES",
    //         code: "FLTACC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN / KICTHEN / GEYSER",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "SWAN NECK",
    //         code: "FLTSNC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN / KICTHEN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },

    //       {
    //         name: "SINK COCK WITH CP FLANGES",
    //         code: "FLTSCC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "KICTHEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "CONCEALED STOP COCK 15MM",
    //         code: "FLTCSC20C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "CONCEALED STOP COCK 20MM",
    //         code: "FLTCSC15C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "CONCEALED STOP COCK 20MM FITTING",
    //         code: "",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "2 IN 1 BIB COCK WITH CP FLANGE",
    //         code: "FLT2WBC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "WC AREA / GARDEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "2 IN 1 ANGLE COCK WITH CP FLANGE",
    //         code: "FLT2ACC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "WC AREA / GARDEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FO AM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "NOZZLE COCK & WASHING BIB COCK WITH CP FLANGE",
    //         code: "FLTNBCC01/FLTWBCC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "GARDEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "CENTRAL HOLE BASIN MIXER",
    //         code: "FLTCHBMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "SINK MIXER",
    //         code: "FLTSMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "KICTHEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "2 IN 1 WALL MIXER WITH L-BEND",
    //         code: "FLT2WWMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "3 IN 1 WALL MIXER WITH L-BEND",
    //         code: "FLT3WWMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "2 IN 1 WALL MIXER WITHOUT L-BEND",
    //         code: "FLTWMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "3 IN 1 WALL MIXER WITHOUT L-BEND",
    //         code: "FLTWMC3C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "NON-TELEPHONIC WALL MIXER",
    //         code: "FLTNTWMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: 'SINGLE LEVER 6"',
    //         code: "FLTSL6C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "35MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: 'SINGLE LEVER 12"',
    //         code: "FLTSL12C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "35MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "DIVERTER WALL SPOUT PLAIN WITH CP FLANGE",
    //         code: "FLTWSC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: " BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "N/A",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "DIVERTER TIP-TON WALL SPOUT  WITH CP FLANGE",
    //         code: "FLTTTWSC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: 'PILLAR COCK 9"',
    //         code: "FLTPC9C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: 'PILLAR COCK 12"',
    //         code: "FLTPC12C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: 'PILLAR COCK 15"',
    //         code: "FLTPC15C01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BASIN AREA",
    //         mounting: "DECK / TABLE MOUNTING",
    //         size: "20MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "5 WAY CONCEALED DIVERTER",
    //         code: "DIV5WC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "40MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "4 WAY HIGH FLOW CONCEALED DIVERTER",
    //         code: "DIVHF45MC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "45MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "4 WAY CONCEALED DIVERTER (40MM)",
    //         code: "DIV4W40MC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "40MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/products images/faucets/FUTURIX/DIV4W40MC01.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "4 WAY CONCEALED DIVERTER (35MM)",
    //         code: "DIV4W35MC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "35MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "5 WAY DIVERTER EXPOSED PART",
    //         code: "FLTEX5WC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "N/A",
    //         quantity: "N/A",
    //         flow: "N/A",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "4 WAY HIGH FLOW DIVERTER EXPOSED PART (45MM)",
    //         code: "FLTEX45MC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "N/A",
    //         quantity: "N/A",
    //         flow: "N/A",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },

    //       {
    //         name: "4 WAY DIVERTER EX POSED PART (40MM)",
    //         code: "FLTEX40MC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "N/A",
    //         quantity: "N/A",
    //         flow: "N/A",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "4 WAY DIVERTER EXPOSED PART (35MM)",
    //         code: "FLTEX35MC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "BATHING AREA",
    //         mounting: "WALL MOUNT",
    //         size: "N/A",
    //         quantity: "N/A",
    //         flow: "N/A",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "SINK MIXER SINGLE LEVER",
    //         code: "FLTSLSMC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "KICTHEN AREA",
    //         mounting: "WALL MOUNT",
    //         size: "35MM",
    //         quantity: 12,
    //         flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //       {
    //         name: "HANDLE (BRASS)",
    //         code: "FLTHAC01",
    //         brand: "FLORENTINE",
    //         finish: "CHROME FINISH",
    //         area: "N/A",
    //         mounting: "N/A",
    //         size: "N/A",
    //         quantity: "N/A",
    //         flow: "N/A",
    //         state: "ALL STATE",
    //         imageSrc: "/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg",
    //         // details:' High-quality sanitaryware for your bathroom.',
    //         details: "",
    //         imagesdata: [],
    //       },
    //     ],
    //   },
    //   {
    //     name: "Square",
    //     imageSrc:
    //       "/public/topproducts/Joerger-Valencia-Edelmessing-mit-weissem-Kristall-Unterputz-Hebelmischer.jpg",
    //  //    details: " High-quality sanitaryware for your bathroom.",
    //       details :'',
    //       products:[
    //            {
    //                name: "PILLAR COCK",
    //                code: "SQUPCC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "LONG BODY WITH CP FLANGES",
    //                code: "SQULBC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHTING",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "BIB COCK WITH CP FLANGES",
    //                code: "SQUBCC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN / KICTHEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "ANGLE COCK WITH CP FLANGES",
    //                code: "SQUACC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN / KICTHEN / GEYSER",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "SWAN NECK",
    //                code: "SQUSNC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN / KICTHEN AREA",
    //                mounting: "DECK / TABLE MOUNTING",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "SINK COCK WITH CP FLANGES",
    //                code: "SQUSCC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "KICTHEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "CONCEALED STOP COCK 15MM",
    //                code: "SQUCSC20C01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "CONCEALED STOP COCK 20MM",
    //                code: "SQUCSC15C01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //         state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "CONCEALED STOP COCK 20MM FITTING",
    //                code: "SQUCSC20MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "2 IN 1 BIB COCK WITH CP FLANGE",
    //                code: "SQU2WBC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "WC AREA / GARDEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "2 IN 1 ANGLE COCK WITH CP FLANGE",
    //                code: "SQU2ACC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "WC AREA / GARDEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "NOZZLE COCK & WASHING BIB COCK WITH CP FLANGE",
    //                code: "SQUNBCC01/SQUWBCC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "GARDEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "CENTRAL HOLE BASIN MIXER",
    //                code: "SQUCHBMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN AREA",
    //                mounting: "DECK / TABLE MOUNTING",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "SINK MIXER",
    //                code: "SQUSMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "KICTHEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "2 IN 1 WALL MIXER WITH L-BEND",
    //                code: "SQU2WWMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "3 IN 1 WALL MIXER WITH L-BEND",
    //                code: "SQU3WWMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "2 IN 1 WALL MIXER WITHOUT L-BEND",
    //                code: "SQUWMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "3 IN 1 WALL MIXER WITHOUT L-BEND",
    //                code: "SQUWMC3C01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "NON-TELEPHONIC WALL MIXER",
    //                code: "SQUNTWMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "SINGLE LEVER 6\"",
    //                code: "SQUSL6C01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN AREA",
    //                mounting: "DECK / TABLE MOUNTING",
    //                size: "35MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "SINGLE LEVER 12\"",
    //                code: "SQUSL12C01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN AREA",
    //                mounting: "DECK / TABLE MOUNTING",
    //                size: "35MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "DIVERTER WALL SPOUT PLAIN WITH CP FLANGE",
    //                code: "SQUWSC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "N/A",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "DIVERTER TIP-TON WALL SPOUT  WITH CP FLANGE",
    //                code: "SQUTTWSC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "20MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "PILLAR COCK 7\"",
    //                code: "SQUPC7C01",
    //                brand: "S QUARE",
    //                finish: "CHROME FINISH",
    //                area: "BASIN AREA",
    //                mounting: "DECK / TABLE MOUNTING",
    //                size: "15MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "5 WAY CONCEALED DIVERTER",
    //                code: "DIV5WC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "40MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "4 WAY HIGH FLOW CONCEALED DIVERTER",
    //                code: "DIVHF45MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "45MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "4 WAY CONCEALED DIVERTER (40MM)",
    //                code: "DIV4W40MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "40MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "4 WAY CONCEALED DIVERTER (35MM)",
    //                code: "DIV4W35MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "35MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "5 WAY DIVERTER EXPOSED PART",
    //                code: "SQUEX5WC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "N/A",
    //                quantity: "N/A",
    //                flow: "N/A",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "4 WAY HIGH FLOW DIVERTER EXPOSED PART (45MM)",
    //                code: "SQUEX45MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "N/A",
    //                quantity: "N/A",
    //                flow: "N/A",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "4 WAY DIVERTER EXPOSED PART (40MM)",
    //                code: "SQUEX40MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "N/A",
    //                quantity: "N/A",
    //                flow: "N/A",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "4 WAY DIV ERTER EXPOSED PART (35MM)",
    //                code: "SQUEX35MC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "BATHING AREA",
    //                mounting: "WALL MOUNT",
    //                size: "N/A",
    //                quantity: "N/A",
    //                flow: "N/A",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "SINK MIXER SINGLE LEVER",
    //                code: "SQUSLSMC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "KICTHEN AREA",
    //                mounting: "WALL MOUNT",
    //                size: "35MM",
    //                quantity: 10,
    //                flow: "FOAM FLOW",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            },
    //            {
    //                name: "HANDLE (BRASS)",
    //                code: "SQUHAC01",
    //                brand: "SQUARE",
    //                finish: "CHROME FINISH",
    //                area: "N/A",
    //                mounting: "N/A",
    //                size: "N/A",
    //                quantity: "N/A",
    //                flow: "N/A",
    //                state: "ALL STATE",
    //                imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
    //                details: '',
    //                imagesdata: []
    //            }
    //        ]

    //   },






    {
        name: "Qubix",
        imageSrc:
          "/public/topproducts/Joerger-Valencia-Edelmessing-mit-weissem-Kristall-Unterputz-Hebelmischer.jpg",
        details: "",
        products:[
          {
              name: "PILLAR COCK",
              code: "QUBPCC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "LONG BODY WITH CP FLANGES",
              code: "QUBLBC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHTING",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "BIB COCK WITH CP FLANGES",
              code: "QUBBCC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN / KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "ANGLE COCK WITH CP FLANGES",
              code: "QUBACC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN / KICTHEN / GEYSER",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SWAN NECK",
              code: "QUBSNC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN / KICTHEN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINK COCK WITH CP FLANGES",
              code: "QUBSCC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CONCEALED STOP COCK 15MM",
              code: "QUBCSC20C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CONCEALED STOP COCK 20MM",
              code: "QUBCSC15C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CONCEALED STOP COCK 20MM FITTING",
              code: "QUBCSC20MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 BIB COCK WITH CP FLANGE",
              code: "QUB2WBC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "WC AREA / GARDEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 ANGLE COCK WITH CP FLANGE",
              code: "QUB2ACC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "WC AREA / GARDEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "NOZZLE COCK & WASHING BIB COCK WITH CP FLANGE",
              code: "QUBNBCC01/QUBWBCC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "GARDEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CENTRAL HOLE BASIN MIXER",
              code: "QUBCHBMC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINK MIXER",
              code: "QUBSMC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 WALL MIXER WITH L-BEND",
              code: "QUB2WWMC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "3 IN 1 WALL MIXER WITH L-BEND",
              code: "QUB3WWMC01",
              brand: "QUBIX",
       finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 WALL MIXER WITHOUT L-BEND",
              code: "QUBWMC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "3 IN 1 WALL MIXER WITHOUT L-BEND",
              code: "QUBWMC3C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "NON-TELEPHONIC WALL MIXER",
              code: "QUBNTWMC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINGLE LEVER 6\"",
              code: "QUBSL6C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINGLE LEVER 12\"",
              code: "QUBSL12C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "35MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "DIVERTER WALL SPOUT PLAIN WITH CP FLANGE",
              code: "QUBWSC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "DIVERTER TIP-TON WALL SPOUT  WITH CP FLANGE",
              code: "QUBTTWSC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: " PILLAR COCK 7\"",
              code: "QUBPC7C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "PILLAR COCK 12\"",
              code: "QUBPC12C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "PILLAR COCK 15\"",
              code: "QUBPC15C01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "5 WAY CONCEALED DIVERTER",
              code: "DIV5WC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "40MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY HIGH FLOW CONCEALED DIVERTER",
              code: "DIVHF45MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "45MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY CONCEALED DIVERTER (40MM)",
              code: "DIV4W40MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "40MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY CONCEALED DIVERTER (35MM)",
              code: "DIV4W35MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "35MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "5 WAY DIVERTER EXPOSED PART",
              code: "QUBEX5WC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: "N/A",
              flow: "N/A",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,100 0_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY HIGH FLOW DIVERTER EXPOSED PART (45MM)",
              code: "QUBEX45MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: "N/A",
              flow: "N/A",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY DIVERTER EXPOSED PART (40MM)",
              code: "QUBEX40MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: "N/A",
              flow: "N/A",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY DIVERTER EXPOSED PART (35MM)",
              code: "QUBEX35MC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: "N/A",
              flow: "N/A",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINK MIXER SINGLE LEVER",
              code: "QUBSLSMC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "35MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "HANDLE (BRASS)",
              code: "QUBHAC01",
              brand: "QUBIX",
              finish: "CHROME FINISH",
              area: "N/A",
              mounting: "N/A",
              size: "N/A",
              quantity: "N/A",
              flow: "N/A",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          }
      ]
      }




      {
        name: "Donald",
        imageSrc:
          "/public/topproducts/Joerger-Valencia-Edelmessing-mit-weissem-Kristall-Unterputz-Hebelmischer.jpg",
        details: "",
        products:[
          {
              name: "PILLAR COCK",
              code: "DONPCC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "LONG BODY WITH CP FLANGES",
              code: "DONLBC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHTING",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "BIB COCK WITH CP FLANGES",
              code: "DONBCC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN / KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "ANGLE COCK WITH CP FLANGES",
              code: "DONACC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN / KICTHEN / GEYSER",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SWAN NECK",
              code: "DONSNC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN / KICTHEN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINK COCK WITH CP FLANGES",
              code: "DONSCC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CONCEALED STOP COCK 15MM",
              code: "DONCSC20C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CONCEALED STOP COCK 20MM",
              code: "DONCSC15C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CONCEALED STOP COCK 20MM FITTING",
              code: "DONCSC20MC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 BIB COCK WITH CP FLANGE",
              code: "DON2WBC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "WC AREA / GARDEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 ANGLE COCK WITH CP FLANGE",
              code: "DON2ACC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "WC AREA / GARDEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "NOZZLE COCK & WASHING BIB COCK WITH CP FLANGE",
              code: "DONNBCC01/DONWBCC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "GARDEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "CENTRAL HOLE BASIN MIXER",
              code: "DONCHBMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINK MIXER",
              code: "DONSMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 WALL MIXER WITH L-BEND",
              code: "DON2WWMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "3 IN 1 WALL MIXER WITH L-BEND",
              code: "DON3WWMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA ",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "2 IN 1 WALL MIXER WITHOUT L-BEND",
              code: "DONWMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "3 IN 1 WALL MIXER WITHOUT L-BEND",
              code: "DONWMC3C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "NON-TELEPHONIC WALL MIXER",
              code: "DONNTWMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINGLE LEVER 6\"",
              code: "DONSL6C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINGLE LEVER 12\"",
              code: "DONSL12C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "35MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "DIVERTER WALL SPOUT PLAIN WITH CP FLANGE",
              code: "DONWSC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "DIVERTER TIP-TON WALL SPOUT  WITH CP FLANGE",
              code: "DONTTWSC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "PILLAR COCK 9\"",
              code: "DONPC9C01",
              brand: "DON ALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "PILLAR COCK 12\"",
              code: "DONPC12C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "PILLAR COCK 15\"",
              code: "DONPC15C01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BASIN AREA",
              mounting: "DECK / TABLE MOUNTING",
              size: "15MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "5 WAY CONCEALED DIVERTER",
              code: "DIV5WC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "40MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY HIGH FLOW CONCEALED DIVERTER",
              code: "DIVHF45MC01",
              brand: "DONAL D",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "45MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY CONCEALED DIVERTER (40MM)",
              code: "DIV4W40MC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "40MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY CONCEALED DIVERTER (35MM)",
              code: "DIV4W35MC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "35MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "5 WAY DIVERTER EXPOSED PART",
              code: "DONEX5WC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY HIGH FLOW DIVERTER EXPOSED PART (45MM)",
              code: "DONEX45MC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY DIVERTER EXPOSED PART (40MM)",
              code: "DONEX40MC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "4 WAY DIVERTER EXPOSED PART (35MM)",
              code: "DONEX35MC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "BATHING AREA",
              mounting: "WALL MOUNT",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: "SINK MIXER SINGLE LEVER",
              code: "DONSLSMC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "KICTHEN AREA",
              mounting: "WALL MOUNT",
              size: "35MM",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          },
          {
              name: " HANDLE (BRASS)",
              code: "DONHAC01",
              brand: "DONALD",
              finish: "CHROME FINISH",
              area: "N/A",
              mounting: "N/A",
              size: "N/A",
              quantity: 10,
              flow: "FOAM FLOW",
              state: "ALL STATE",
              imageSrc: '/public/515lDt3ygFL._AC_UF1000,1000_QL80_.jpg',
              details: '',
              imagesdata: []
          }
      ]
      },